[package]
name = "bls-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
clap_derive = "4.5.18"
hex = "0.4.3"
serde_json = "1.0.133"
sha3 = "0.11.0-pre.4"
sylow = "0.1.1"
